translate_start = {
    "СТАРТ": "START",
    "Сменить\n"
    "язык": "Switch\n"
    "language",
    "Виселица": "Gallows",
}

words_hardware = {
    "bus": "шина",
    "cable": "кабель",
    "central processing unit": "центральный процессор",
    "computer case": "корпус",
    "device": "устройство",
    "fan": "вентилятор",
    "graphics card": "видеокарта",
    "graphics processing unit": "графический процессор",
    "hard disk drive": "жесткий диск",
    "laptop": "ноутбук",
    "light-emitting diode": "светодиод",
    "motherboard": "материнская плата",
    "network card": "сетевая карта",
    "port": "порт",
    "power supply unit": "блок питания",
    "solid-state drive": "твердотельный накопитель",
    "sound card": "звуковая карта",
    "storage device": "накопитель",
    "touch screen": "сенсорный экран",
    "air cooling": "воздушное охлаждение",
    "expansion card": "расширительная карта",
    "optical disk drive": "оптический привод",
    "uninterruptible power source": "источник бесперебойного питания",
    "random-access memory": "оперативная память",
    "read-only memory": "постоянное запоминающее устройство",
    "removable media": "съемные носители",
    "water cooling": "водяное охлаждение",
    "monitor": "монитор",
    "printer": "принтер",
    "speaker": "акустическая колонка",
    "headphones": "наушники",
    "keyboard": "клавиатура",
    "mouse": "мышь",
    "scanner": "сканер",
    "digital camera": "цифровая камера",
    "joystick": "джойстик"
}

words_software = {
    "compiler": "компилятор",
    "database": "база данных",
    "debugger": "отладчик",
    "desktop application": "приложение для настольного компьютера",
    "device driver": "драйвер устройства",
    "graphical user interface": "графический пользовательский интерфейс",
    "kernel": "ядро",
    "mobile application": "мобильное приложение",
    "plug-in": "расширение",
    "programming language": "язык программирования",
    "query": "запрос",
    "scroll bar": "полоса прокрутки",
    "snapshot": "снимок состояния системы",
    "spreadsheet": "электронная таблица",
    "status bar": "строка состояния",
    "template": "шаблон",
    "version control system": "система контроля версий",
    "web application": "веб-приложение",
    "word processor": "текстовый процессор",
    "text editor": "текстовый редактор",
    "utility": "утилита",
    "acceptance testing": "приемочное тестирование",
    "agile methodology": "гибкая методология разработки",
    "algorithm": "алгоритм",
    "array": "массив",
    "encoding": "кодировка",
    "enterprise application": "корпоративное приложение",
    "executable": "исполняемый файл",
    "interpreter": "интерпретатор",
    "operating system": "операционная система",
    "application software": "прикладное программное обеспечение",
    "aspect-oriented programming": "аспектно-ориентированное программирование",
    "binary data": "двоичные данные",
    "commercial software": "платное программное обеспечение",
    "data": "данные",
    "data processing": "обработка данных",
    "extreme programming": "экстремальное программирование",
    "firmware": "микропрограмма",
    "freeware": "бесплатное программное обеспечение",
    "incremental development": "инкрементная модель разработки",
    "integrated development environment": "интегрированная среда разработки",
    "iterative development": "итеративная модель разработки",
    "malicious software": "вредоносное программное обеспечение",
    "object-oriented programming": "объектно-ориентированное программирование",
    "prototyping": "создание прототипа",
    "rapid application development": "быстрая разработка приложений",
    "regression testing": "регрессионное тестирование",
    "runtime": "среда выполнения кода",
    "server software": "серверное программное обеспечение",
    "spiral development": "спиральная модель разработки",
    "spyware": "программа-шпион",
    "system software": "системное программное обеспечение",
    "unit testing": "модульное тестирование",
    "waterfall model": "каскадная модель разработки"
}

words_internet = {
    "bookmark": "закладка",
    "bridge": "мост",
    "browser": "браузер, обозреватель",
    "domain": "домен",
    "firewall": "межсетевой экран",
    "gateway": "шлюз",
    "hyperlink": "гиперссылка",
    "node": "узел сети",
    "packet": "пакет",
    "patch cord": "коммутационный кабель",
    "router": "маршрутизатор",
    "search engine": "поисковая система",
    "subdomain": "поддомен",
    "switch": "коммутатор",
    "website": "веб-сайт",
    "wireless network": "беспроводная сеть",
    "bandwidth": "пропускная способность",
    "broadband": "широкополосный доступ в интернет",
    "client-server architecture": "клиент-серверная архитектура",
    "cloud computing": "облачные вычисления",
    "cloud storage": "облачное хранилище данных",
    "dynamic host configuration protocol ": "протокол динамической настройки узла",
    "domain name system": "система доменных имен",
    "instant messaging": "обмен мгновенными сообщениями",
    "Internet service provider": "интернет-провайдер",
    "local area network": "локальная сеть",
    "latency": "задержка",
    "media access control address": "аппаратный адрес",
    "peer-to-peer": "одноранговая сеть",
    "twisted pair": "витая пара",
    "voice over IP": "голосовая связь через интернет",
    "wide area network": "глобальная сеть"
}
