words_hardware = {
    "bus": ["шина", "src/sound/words/bus.mp3"],
    "cable": ["кабель", "src/sound/words/cabel.mp3"],
    "central processing unit": ["центральный процессор", "src/sound/words/cpu.mp3"],
    "computer case": ["корпус", "src/sound/words/computer_case.mp3"],
    "device": ["устройство", "src/sound/words/device.mp3"],
    "fan": ["вентилятор", "src/sound/words/fan.mp3"],
    "graphics card": ["видеокарта", "src/sound/words/graphics_card.mp3"],
    "graphics processing unit": ["графический процессор", "src/sound/words/graphics_processor.mp3"],
    "hard disk drive": ["жесткий диск", "src/sound/words/hard_disk.mp3"],
    "laptop": ["ноутбук", "src/sound/words/laptop.mp3"],
    "light-emitting diode": ["светодиод", "src/sound/words/led.mp3"],
    "motherboard": ["материнская плата", "src/sound/words/motherboard.mp3"],
    "network card": ["сетевая карта", "src/sound/words/network_card.mp3"],
    "port": ["порт", "src/sound/words/port.mp3"],
    "power supply unit": ["блок питания", "src/sound/words/power_supply_unit.mp3"],
    "solid-state drive": ["твердотельный накопитель", "src/sound/words/ssd.mp3"],
    "sound card": ["звуковая карта", "src/sound/words/sound_card.mp3"],
    "storage device": ["накопитель", "src/sound/words/storage.mp3"],
    "touch screen": ["сенсорный экран", "src/sound/words/touch_screen.mp3"],
    "air cooling": ["воздушное охлаждение", "src/sound/words/air_cooling.mp3"],
    "expansion card": ["расширительная карта", "src/sound/words/expansion_card.mp3"],
    "optical disk drive": ["оптический привод", "src/sound/words/optical_disk_drive.mp3"],
    "uninterruptible power source": ["источник бесперебойного питания", "src/sound/words/power_source.mp3"],
    "random-access memory": ["оперативная память", "src/sound/words/ram.mp3"],
    "read-only memory": ["постоянное запоминающее устройство", "src/sound/words/rom.mp3"],
    "removable media": ["съемные носители", "src/sound/words/removable_media.mp3"],
    "water cooling": ["водяное охлаждение", "src/sound/words/water_cooling.mp3"],
    "monitor": ["монитор", "src/sound/words/monitor.mp3"],
    "printer": ["принтер", "src/sound/words/printer.mp3"],
    "speaker": ["акустическая колонка", "src/sound/words/speaker.mp3"],
    "headphones": ["наушники", "src/sound/words/headphones.mp3"],
    "keyboard": ["клавиатура", "src/sound/words/keyboard.mp3"],
    "mouse": ["мышь", "src/sound/words/mouse.mp3"],
    "scanner": ["сканер", "src/sound/words/scanner.mp3"],
    "digital camera": ["цифровая камера", "src/sound/words/digital_camera.mp3"],
    "joystick": ["джойстик", "src/sound/words/joystick.mp3"],
}

words_software = {
    "compiler": ["компилятор", "src/sound/words/compiler.mp3"],
    "database": ["база данных", "src/sound/words/database.mp3"],
    "debugger": ["отладчик", "src/sound/words/debugger.mp3"],
    "desktop application": ["приложение для настольного компьютера", "src/sound/words/desktop_application.mp3"],
    "device driver": ["драйвер устройства", "src/sound/words/device_driver.mp3"],
    "graphical user interface": ["графический пользовательский интерфейс", "src/sound/words/graphical_user_interface.mp3"],
    "kernel": ["ядро", "src/sound/words/kernel.mp3"],
    "mobile application": ["мобильное приложение", "src/sound/words/mobile_application.mp3"],
    "plug-in": ["расширение", "src/sound/words/plug_in.mp3"],
    "programming language": ["язык программирования", "src/sound/words/programming_language.mp3"],
    "query": ["запрос", "src/sound/words/query.mp3"],
    "scroll bar": ["полоса прокрутки", "src/sound/words/scroll_bar.mp3"],
    "snapshot": ["снимок состояния системы", "src/sound/words/snapshot.mp3"],
    "spreadsheet": ["электронная таблица", "src/sound/words/spreadsheet.mp3"],
    "status bar": ["строка состояния", "src/sound/words/status_bar.mp3"],
    "template": ["шаблон", "src/sound/words/template.mp3"],
    "version control system": ["система контроля версий", "src/sound/words/version_control_system.mp3"],
    "web application": ["веб-приложение", "src/sound/words/web_application.mp3"],
    "word processor": ["текстовый процессор", "src/sound/words/word_processor.mp3"],
    "text editor": ["текстовый редактор", "src/sound/words/text_editor.mp3"],
    "utility": ["утилита", "src/sound/words/utility.mp3"],
    "acceptance testing": ["приемочное тестирование", "src/sound/words/acceptance_testing.mp3"],
    "agile methodology": ["гибкая методология разработки", "src/sound/words/agile_methodology.mp3"],
    "algorithm": ["алгоритм", "src/sound/words/algorithm.mp3"],
    "array": ["массив", "src/sound/words/array.mp3"],
    "encoding": ["кодировка", "src/sound/words/encoding.mp3"],
    "enterprise application": ["корпоративное приложение", "src/sound/words/enterprise_application.mp3"],
    "executable": ["исполняемый файл", "src/sound/words/executable.mp3"],
    "interpreter": ["интерпретатор", "src/sound/words/interpreter.mp3"],
    "operating system": ["операционная система", "src/sound/words/operating_system.mp3"],
    "application software": ["прикладное программное обеспечение", "src/sound/words/application_software.mp3"],
    "aspect-oriented programming": ["аспектно-ориентированное программирование", "src/sound/words/aspect_oriented_programming.mp3"],
    "binary data": ["двоичные данные", "src/sound/words/binary_data.mp3"],
    "commercial software": ["платное программное обеспечение", "src/sound/words/commercial_software.mp3"],
    "data": ["данные", "src/sound/words/data.mp3"],
    "data processing": ["обработка данных", "src/sound/words/data_processing.mp3"],
    "extreme programming": ["экстремальное программирование", "src/sound/words/extreme_programming.mp3"],
    "firmware": ["микропрограмма", "src/sound/words/firmware.mp3"],
    "freeware": ["бесплатное программное обеспечение", "src/sound/words/freeware.mp3"],
    "incremental development": ["инкрементная модель разработки", "src/sound/words/incremental_development.mp3"],
    "integrated development environment": ["интегрированная среда разработки", "src/sound/words/integrated_development_environment.mp3"],
    "iterative development": ["итеративная модель разработки", "src/sound/words/iterative_development.mp3"],
    "malicious software": ["вредоносное программное обеспечение", "src/sound/words/malicious_software.mp3"],
    "object-oriented programming": ["объектно-ориентированное программирование", "src/sound/words/object_oriented_programming.mp3"],
    "prototyping": ["создание прототипа", "src/sound/words/prototyping.mp3"],
    "rapid application development": ["быстрая разработка приложений", "src/sound/words/rapid_application_development.mp3"],
    "regression testing": ["регрессионное тестирование", "src/sound/words/regression_testing.mp3"],
    "runtime": ["среда выполнения кода", "src/sound/words/runtime.mp3"],
    "server software": ["серверное программное обеспечение", "src/sound/words/server_software.mp3"],
    "spiral development": ["спиральная модель разработки", "src/sound/words/spiral_development.mp3"],
    "spyware": ["программа-шпион", "src/sound/words/spyware.mp3"],
    "system software": ["системное программное обеспечение", "src/sound/words/system_software.mp3"],
    "unit testing": ["модульное тестирование", "src/sound/words/unit_testing.mp3"],
    "waterfall model": ["каскадная модель разработки", "src/sound/words/waterfall_model.mp3"],
}

words_internet = {
    "bookmark": ["закладка", "src/sound/words/bookmark.mp3"],
    "bridge": ["мост", "src/sound/words/bridge.mp3"],
    "browser": ["браузер", "src/sound/words/browser.mp3"],
    "domain": ["домен", "src/sound/words/domain.mp3"],
    "firewall": ["межсетевой экран", "src/sound/words/firewall.mp3"],
    "gateway": ["шлюз", "src/sound/words/gateway.mp3"],
    "hyperlink": ["гиперссылка", "src/sound/words/hyperlink.mp3"],
    "node": ["узел сети", "src/sound/words/node.mp3"],
    "packet": ["пакет", "src/sound/words/packet.mp3"],
    "patch cord": ["коммутационный кабель", "src/sound/words/patch_cord.mp3"],
    "router": ["маршрутизатор", "src/sound/words/router.mp3"],
    "search engine": ["поисковая система", "src/sound/words/search_engine.mp3"],
    "subdomain": ["поддомен", "src/sound/words/subdomain.mp3"],
    "switch": ["коммутатор", "src/sound/words/switch.mp3"],
    "website": ["веб-сайт", "src/sound/words/website.mp3"],
    "wireless network": ["беспроводная сеть", "src/sound/words/wireless_network.mp3"],
    "bandwidth": ["пропускная способность", "src/sound/words/bandwidth.mp3"],
    "broadband": ["широкополосный доступ в интернет", "src/sound/words/broadband.mp3"],
    "client-server architecture": ["клиент-серверная архитектура", "src/sound/words/client_server_architecture.mp3"],
    "cloud computing": ["облачные вычисления", "src/sound/words/cloud_computing.mp3"],
    "cloud storage": ["облачное хранилище данных", "src/sound/words/cloud_storage.mp3"],
    "dynamic host configuration protocol": ["протокол динамической настройки узла", "src/sound/words/dynamic_host_configuration_protocol.mp3"],
    "domain name system": ["система доменных имен", "src/sound/words/domain_name_system.mp3"],
    "instant messaging": ["обмен мгновенными сообщениями", "src/sound/words/instant_messaging.mp3"],
    "Internet service provider": ["интернет-провайдер", "src/sound/words/internet_service_provider.mp3"],
    "local area network": ["локальная сеть", "src/sound/words/local_area_network.mp3"],
    "latency": ["задержка", "src/sound/words/latency.mp3"],
    "media access control address": ["аппаратный адрес", "src/sound/words/media_access_control_address.mp3"],
    "peer-to-peer": ["одноранговая сеть", "src/sound/words/peer_to_peer.mp3"],
    "twisted pair": ["витая пара", "src/sound/words/twisted_pair.mp3"],
    "voice over ip": ["голосовая связь через интернет", "src/sound/words/voice_over_ip.mp3"],
    "wide area network": ["глобальная сеть", "src/sound/words/wide_area_network.mp3"],
}


words_ai = {
    "artificial intelligence": ["искусственный интеллект", "src/sound/words/artificial_intelligence.mp3"],
    "machine learning": ["машинное обучение", "src/sound/words/machine_learning.mp3"],
    "deep learning": ["глубокое обучение", "src/sound/words/deep_learning.mp3"],
    "neural network": ["нейронная сеть", "src/sound/words/neural_network.mp3"],
    "natural language processing": ["обработка естественного языка", "src/sound/words/natural_language_processing.mp3"],
    "computer vision": ["компьютерное зрение", "src/sound/words/computer_vision.mp3"],
    "reinforcement learning": ["обучение с подкреплением", "src/sound/words/reinforcement_learning.mp3"],
    "supervised learning": ["обучение с учителем", "src/sound/words/supervised_learning.mp3"],
    "unsupervised learning": ["обучение без учителя", "src/sound/words/unsupervised_learning.mp3"],
    "algorithm": ["алгоритм", "src/sound/words/algorithm.mp3"],
    "data mining": ["поиск данных", "src/sound/words/data_mining.mp3"],
    "predictive analytics": ["прогностическая аналитика", "src/sound/words/predictive_analytics.mp3"],
    "automation": ["автоматизация", "src/sound/words/automation.mp3"],
    "chatbot": ["чат-бот", "src/sound/words/chatbot.mp3"],
    "computer program": ["компьютерная программа", "src/sound/words/computer_program.mp3"],
    "data analysis": ["анализ данных", "src/sound/words/data_analysis.mp3"],
    "data science": ["наука о данных", "src/sound/words/data_science.mp3"],
    "feature engineering": ["инженерия признаков", "src/sound/words/feature_engineering.mp3"],
    "knowledge representation": ["представление знаний", "src/sound/words/knowledge_representation.mp3"],
    "pattern recognition": ["распознавание образов", "src/sound/words/pattern_recognition.mp3"],
    "speech recognition": ["распознавание речи", "src/sound/words/speech_recognition.mp3"],
    "algorithmic bias": ["алгоритмический уклон", "src/sound/words/algorithmic_bias.mp3"],
    "augmented reality": ["дополненная реальность", "src/sound/words/augmented_reality.mp3"],
    "big data": ["большие данные", "src/sound/words/big_data.mp3"],
    "cloud computing": ["облачные вычисления", "src/sound/words/cloud_computing.mp3"],
    "computer vision": ["компьютерное зрение", "src/sound/words/computer_vision.mp3"],
    "data engineering": ["инженерия данных", "src/sound/words/data_engineering.mp3"],
    "ethics in AI": ["этика в искусственном интеллекте", "src/sound/words/ethics_in_ai.mp3"],
    "fuzzy logic": ["нечеткая логика", "src/sound/words/fuzzy_logic.mp3"],
    "intelligent agent": ["интеллектуальный агент", "src/sound/words/intelligent_agent.mp3"],
    "machine translation": ["машинный перевод", "src/sound/words/machine_translation.mp3"],
    "predictive modeling": ["прогностическое моделирование", "src/sound/words/predictive_modeling.mp3"],
    "robotics": ["робототехника", "src/sound/words/robotics.mp3"],
    "sentiment analysis": ["анализ настроений", "src/sound/words/sentiment_analysis.mp3"],
    "smart home": ["умный дом", "src/sound/words/smart_home.mp3"],
    "supervised learning": ["обучение с учителем", "src/sound/words/supervised_learning.mp3"],
    "unsupervised learning": ["обучение без учителя", "src/sound/words/unsupervised_learning.mp3"],
    "virtual reality": ["виртуальная реальность", "src/sound/words/virtual_reality.mp3"],
}

words_design = {
    "design": ["дизайн", "src/sound/words/design.mp3"],
    "user interface": ["пользовательский интерфейс", "src/sound/words/user_interface.mp3"],
    "user experience": ["пользовательский опыт", "src/sound/words/user_experience.mp3"],
    "graphic design": ["графический дизайн", "src/sound/words/graphic_design.mp3"],
    "web design": ["веб-дизайн", "src/sound/words/web_design.mp3"],
    "interaction design": ["дизайн взаимодействия", "src/sound/words/interaction_design.mp3"],
    "typography": ["типографика", "src/sound/words/typography.mp3"],
    "color theory": ["теория цвета", "src/sound/words/color_theory.mp3"],
    "wireframe": ["черновик", "src/sound/words/wireframe.mp3"],
    "mockup": ["макет", "src/sound/words/mockup.mp3"],
    "prototype": ["прототип", "src/sound/words/prototype.mp3"],
    "responsive design": ["отзывчивый дизайн", "src/sound/words/responsive_design.mp3"],
    "information architecture": ["информационная архитектура", "src/sound/words/information_architecture.mp3"],
    "visual hierarchy": ["визуальная иерархия", "src/sound/words/visual_hierarchy.mp3"],
    "whitespace": ["отступы", "src/sound/words/whitespace.mp3"],
    "grid system": ["сетка", "src/sound/words/grid_system.mp3"],
    "brand identity": ["идентичность бренда", "src/sound/words/brand_identity.mp3"],
    "logo design": ["дизайн логотипа", "src/sound/words/logo_design.mp3"],
    "vector graphics": ["векторная графика", "src/sound/words/vector_graphics.mp3"],
    "raster graphics": ["растровая графика", "src/sound/words/raster_graphics.mp3"],
    "design thinking": ["дизайн-мышление", "src/sound/words/design_thinking.mp3"],
    "usability": ["удобство использования", "src/sound/words/usability.mp3"],
    "motion design": ["дизайн движения", "src/sound/words/motion_design.mp3"],
    "flat design": ["плоский дизайн", "src/sound/words/flat_design.mp3"],
    "skeuomorphism": ["скьюоморфизм", "src/sound/words/skeuomorphism.mp3"],
    "material design": ["материальный дизайн", "src/sound/words/material_design.mp3"],
    "design system": ["дизайн-система", "src/sound/words/design_system.mp3"],
    "gradient": ["градиент", "src/sound/words/gradient.mp3"],
    "pixel": ["пиксель", "src/sound/words/pixel.mp3"],
}

words_cybersecurity = {
    "cybersecurity": ["кибербезопасность", "src/sound/words/cybersecurity.mp3"],
    "antivirus": ["антивирус", "src/sound/words/antivirus.mp3"],
    "malware": ["вредоносное программное обеспечение", "src/sound/words/malware.mp3"],
    "phishing": ["фишинг", "src/sound/words/phishing.mp3"],
    "encryption": ["шифрование", "src/sound/words/encryption.mp3"],
    "authentication": ["аутентификация", "src/sound/words/authentication.mp3"],
    "authorization": ["авторизация", "src/sound/words/authorization.mp3"],
    "intrusion detection system": ["система обнаружения вторжений", "src/sound/words/intrusion_detection_system.mp3"],
    "incident response": ["реагирование на инциденты", "src/sound/words/incident_response.mp3"],
    "vulnerability assessment": ["оценка уязвимостей", "src/sound/words/vulnerability_assessment.mp3"],
    "penetration testing": ["тестирование на проникновение", "src/sound/words/penetration_testing.mp3"],
    "security patch": ["патч безопасности", "src/sound/words/security_patch.mp3"],
    "zero-day exploit": ["эксплойт нулевого дня", "src/sound/words/zero_day_exploit.mp3"],
    "network security": ["сетевая безопасность", "src/sound/words/network_security.mp3"],
    "endpoint security": ["безопасность конечных точек", "src/sound/words/endpoint_security.mp3"],
    "security audit": ["аудит безопасности", "src/sound/words/security_audit.mp3"],
    "two-factor authentication": ["двухфакторная аутентификация", "src/sound/words/two_factor_authentication.mp3"],
    "biometric authentication": ["биометрическая аутентификация", "src/sound/words/biometric_authentication.mp3"],
    "cyber threat intelligence": ["разведка киберугроз", "src/sound/words/cyber_threat_intelligence.mp3"],
    "security incident": ["инцидент безопасности", "src/sound/words/security_incident.mp3"],
    "denial of service": ["отказ в обслуживании", "src/sound/words/denial_of_service.mp3"],
    "social engineering": ["социальная инженерия", "src/sound/words/social_engineering.mp3"],
    "patch management": ["управление патчами", "src/sound/words/patch_management.mp3"],
    "cryptography": ["криптография", "src/sound/words/cryptography.mp3"],
    "security policy": ["политика безопасности", "src/sound/words/security_policy.mp3"],
    "security breach": ["нарушение безопасности", "src/sound/words/security_breach.mp3"],
}
