translate_start = {
    "СТАРТ": "START",
    "Сменить\n"
    "язык": "Switch\n"
    "language",
    "Виселица": "Gallows",
}

words_hardware = {
    "bus": "шина",
    "cable": "кабель",
    "central processing unit (CPU)": "центральный процессор",
    "computer case": "корпус",
    "device": "устройство",
    "fan": "вентилятор",
    "graphics card": "видеокарта",
    "graphics processing unit (GPU)": "графический процессор",
    "hard disk drive (HDD)": "жесткий диск",
    "laptop": "ноутбук",
    "light-emitting diode (LED)": "светодиод",
    "motherboard (mainboard)": "материнская плата",
    "network card": "сетевая карта",
    "port": "порт",
    "power supply unit (PSU)": "блок питания",
    "solid-state drive (SSD)": "твердотельный накопитель",
    "sound card": "звуковая карта",
    "storage device": "накопитель",
    "touch screen": "сенсорный экран",
    "air cooling": "воздушное охлаждение",
    "expansion card": "расширительная карта",
    "optical disk drive": "оптический привод",
    "uninterruptible power source (UPS)": "источник бесперебойного питания",
    "random-access memory (RAM)": "оперативная память",
    "read-only memory (ROM)": "постоянное запоминающее устройство",
    "removable media": "съемные носители",
    "water cooling": "водяное охлаждение",
    "monitor": "монитор",
    "printer": "принтер",
    "speaker": "акустическая колонка",
    "headphones": "наушники",
    "keyboard": "клавиатура",
    "mouse": "мышь",
    "scanner": "сканер",
    "digital camera": "цифровая камера",
    "joystick": "джойстик"
}

words_software = {
    "compiler": "компилятор",
    "database": "база данных",
    "debugger": "отладчик",
    "desktop application/app": "приложение для настольного компьютера",
    "device driver": "драйвер устройства",
    "graphical user interface (GUI)": "графический пользовательский интерфейс",
    "kernel": "ядро (операционной системы)",
    "mobile application/app": "мобильное приложение",
    "plug-in (plugin)": "плагин, расширение, дополнительный программный модуль",
    "programming language": "язык программирования",
    "query": "запрос",
    "scroll bar": "полоса прокрутки",
    "snapshot": "снимок состояния системы",
    "spreadsheet": "электронная таблица",
    "status bar": "строка состояния",
    "template": "шаблон",
    "version control system (VCS)": "система контроля версий",
    "web application, web app": "веб-приложение",
    "word processor": "текстовый процессор",
    "text editor": "текстовый редактор",
    "utility": "утилита (служебная программа)",
    "acceptance testing": "приемочное тестирование",
    "agile methodology": "гибкая методология разработки",
    "algorithm": "алгоритм",
    "array": "массив",
    "encoding": "кодировка",
    "enterprise application": "корпоративное приложение",
    "executable (file)": "исполняемый файл",
    "interpreter": "интерпретатор",
    "operating system (OS)": "операционная система",
    "application software": "прикладное программное обеспечение",
    "aspect-oriented programming (AOP)": "аспектно-ориентированное программирование",
    "binary data": "двоичные данные",
    "commercial software": "платное программное обеспечение",
    "data": "данные, информация",
    "data processing": "обработка данных",
    "extreme programming": "экстремальное программирование",
    "firmware": "прошивка, микропрограмма",
    "freeware": "бесплатное программное обеспечение",
    "incremental development": "инкрементная модель разработки",
    "integrated development environment (IDE)": "интегрированная среда разработки",
    "iterative development": "итеративная модель разработки",
    "malicious software (malware)": "вредоносное программное обеспечение",
    "object-oriented programming (OOP)": "объектно-ориентированное программирование",
    "open source software": "программное обеспечение с открытым исходным кодом",
    "prototyping": "создание прототипа, прототипирование",
    "rapid application development (RAD)": "быстрая разработка приложений (методология)",
    "regression testing": "регрессионное тестирование",
    "runtime (runtime environment)": "среда выполнения кода",
    "server software": "серверное программное обеспечение",
    "spiral development": "спиральная модель разработки",
    "spyware": "программа-шпион, шпионское программное обеспечение",
    "system software": "системное программное обеспечение",
    "unit testing": "модульное (блочное, компонентное) тестирование",
    "waterfall model": "каскадная модель разработки"
}

words_internet = {
    "bookmark": "закладка (в браузере)",
    "bridge": "мост",
    "browser": "браузер, обозреватель",
    "domain": "домен",
    "firewall": "брандмауэр, межсетевой экран",
    "gateway": "шлюз",
    "hyperlink": "гиперссылка",
    "node": "узел сети",
    "packet": "пакет",
    "patch cord": "коммутационный кабель, патч-корд",
    "router": "маршрутизатор, роутер",
    "search engine": "поисковая система",
    "subdomain": "поддомен, субдомен",
    "switch": "коммутатор, свитч",
    "website": "веб-сайт, веб-узел",
    "wireless network": "беспроводная сеть",
    "bandwidth": "пропускная способность (канала передачи данных)",
    "broadband": "широкополосный доступ в интернет",
    "client-server architecture": "клиент-серверная архитектура",
    "cloud computing": "облачные вычисления",
    "cloud storage": "облачное хранилище данных",
    "dynamic host configuration protocol (DHCP)": "протокол динамической настройки узла",
    "domain name system (DNS)": "система доменных имен",
    "instant messaging (IM)": "обмен мгновенными сообщениями",
    "Internet service provider (ISP)": "интернет-провайдер",
    "local area network (LAN)": "локальная сеть",
    "latency": "задержка, период ожидания",
    "media access control (MAC) address": "аппаратный адрес, MAC-адрес",
    "peer-to-peer (P2P)": "одноранговая сеть, пиринговая сеть",
    "twisted pair": "витая пара",
    "voice over IP (VoIP)": "голосовая связь через интернет, IP-телефония",
    "wide area network (WAN)": "глобальная сеть, широкомасштабная сеть"
}
